// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xid/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the xid module's genesis state.
type GenesisState struct {
	// params defines the module parameters
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// tlds is the list of registered top-level domains
	Tlds []TLDConfig `protobuf:"bytes,2,rep,name=tlds,proto3" json:"tlds"`
	// names is the list of all registered name entries
	Names []NameEntry `protobuf:"bytes,3,rep,name=names,proto3" json:"names"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ab0676c66cde9, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTlds() []TLDConfig {
	if m != nil {
		return m.Tlds
	}
	return nil
}

func (m *GenesisState) GetNames() []NameEntry {
	if m != nil {
		return m.Names
	}
	return nil
}

// Params defines the xid module parameters.
type Params struct {
	// fee_denom is the denomination used for registration fees
	FeeDenom string `protobuf:"bytes,1,opt,name=fee_denom,json=feeDenom,proto3" json:"fee_denom,omitempty"`
	// min_name_length is the minimum allowed name length
	MinNameLength uint32 `protobuf:"varint,2,opt,name=min_name_length,json=minNameLength,proto3" json:"min_name_length,omitempty"`
	// max_name_length is the maximum allowed name length
	MaxNameLength uint32 `protobuf:"varint,3,opt,name=max_name_length,json=maxNameLength,proto3" json:"max_name_length,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ab0676c66cde9, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFeeDenom() string {
	if m != nil {
		return m.FeeDenom
	}
	return ""
}

func (m *Params) GetMinNameLength() uint32 {
	if m != nil {
		return m.MinNameLength
	}
	return 0
}

func (m *Params) GetMaxNameLength() uint32 {
	if m != nil {
		return m.MaxNameLength
	}
	return 0
}

// NameEntry bundles a name record with its profile and DNS records for genesis export.
type NameEntry struct {
	Record     NameRecord  `protobuf:"bytes,1,opt,name=record,proto3" json:"record"`
	Profile    *Profile    `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	DnsRecords []DNSRecord `protobuf:"bytes,3,rep,name=dns_records,json=dnsRecords,proto3" json:"dns_records"`
}

func (m *NameEntry) Reset()         { *m = NameEntry{} }
func (m *NameEntry) String() string { return proto.CompactTextString(m) }
func (*NameEntry) ProtoMessage()    {}
func (*NameEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ab0676c66cde9, []int{2}
}
func (m *NameEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NameEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NameEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NameEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameEntry.Merge(m, src)
}
func (m *NameEntry) XXX_Size() int {
	return m.Size()
}
func (m *NameEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NameEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NameEntry proto.InternalMessageInfo

func (m *NameEntry) GetRecord() NameRecord {
	if m != nil {
		return m.Record
	}
	return NameRecord{}
}

func (m *NameEntry) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *NameEntry) GetDnsRecords() []DNSRecord {
	if m != nil {
		return m.DnsRecords
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "xid.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "xid.v1.Params")
	proto.RegisterType((*NameEntry)(nil), "xid.v1.NameEntry")
}

func init() { proto.RegisterFile("xid/v1/genesis.proto", fileDescriptor_dd5ab0676c66cde9) }

var fileDescriptor_dd5ab0676c66cde9 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4f, 0x8f, 0xd2, 0x40,
	0x18, 0xc6, 0x3b, 0xcb, 0x5a, 0x97, 0xa9, 0xeb, 0xea, 0x84, 0x43, 0xc5, 0xa4, 0x20, 0x07, 0x83,
	0x51, 0x5b, 0xc1, 0x8b, 0xd1, 0x1b, 0x62, 0xbc, 0x10, 0x62, 0x8a, 0x27, 0x2f, 0x4d, 0xa1, 0xd3,
	0x32, 0x09, 0x33, 0xd3, 0x74, 0x46, 0x52, 0x4e, 0x7e, 0x05, 0x8f, 0x1c, 0x89, 0x9f, 0x86, 0x23,
	0x47, 0x4f, 0xc6, 0xc0, 0xc5, 0x8f, 0x61, 0x3a, 0x33, 0xa0, 0x64, 0x6f, 0x9d, 0xe7, 0xf9, 0xbd,
	0x7f, 0xf2, 0xf4, 0x85, 0x8d, 0x92, 0x24, 0xc1, 0xb2, 0x17, 0x64, 0x98, 0x61, 0x41, 0x84, 0x9f,
	0x17, 0x5c, 0x72, 0x64, 0x97, 0x24, 0xf1, 0x97, 0xbd, 0x66, 0x23, 0xe3, 0x19, 0x57, 0x52, 0x50,
	0x7d, 0x69, 0xb7, 0xf9, 0x68, 0xc6, 0x05, 0xe5, 0x22, 0xd2, 0x86, 0x7e, 0x18, 0xeb, 0x81, 0x69,
	0x57, 0xd5, 0x2b, 0xa5, 0xb3, 0x06, 0xf0, 0xde, 0x47, 0xdd, 0x7c, 0x22, 0x63, 0x89, 0xd1, 0x0b,
	0x68, 0xe7, 0x71, 0x11, 0x53, 0xe1, 0x82, 0x36, 0xe8, 0x3a, 0xfd, 0xfb, 0xbe, 0x1e, 0xe6, 0x7f,
	0x52, 0xea, 0xe0, 0x72, 0xfb, 0xab, 0x65, 0x85, 0x86, 0x41, 0xcf, 0xe1, 0xa5, 0x5c, 0x24, 0xc2,
	0xbd, 0x68, 0xd7, 0xba, 0x4e, 0xff, 0xe1, 0x91, 0xfd, 0x3c, 0x1a, 0xbe, 0xe7, 0x2c, 0x25, 0x99,
	0xc1, 0x15, 0x84, 0x5e, 0xc2, 0x3b, 0x2c, 0xa6, 0x58, 0xb8, 0xb5, 0x73, 0x7a, 0x1c, 0x53, 0xfc,
	0x81, 0xc9, 0x62, 0x65, 0x68, 0x4d, 0x75, 0xbe, 0x41, 0x5b, 0xcf, 0x44, 0x8f, 0x61, 0x3d, 0xc5,
	0x38, 0x4a, 0x30, 0xe3, 0x54, 0xad, 0x55, 0x0f, 0xaf, 0x52, 0x8c, 0x87, 0xd5, 0x1b, 0x3d, 0x85,
	0x37, 0x94, 0xb0, 0xa8, 0xaa, 0x89, 0x16, 0x98, 0x65, 0x72, 0xee, 0x5e, 0xb4, 0x41, 0xf7, 0x3a,
	0xbc, 0xa6, 0x84, 0x55, 0xad, 0x47, 0x4a, 0x54, 0x5c, 0x5c, 0x9e, 0x71, 0x35, 0xc3, 0xc5, 0xe5,
	0x3f, 0xee, 0xed, 0xd5, 0x7a, 0xd3, 0xb2, 0xfe, 0x6c, 0x5a, 0xa0, 0xf3, 0x03, 0xc0, 0xfa, 0x69,
	0x37, 0xf4, 0x0a, 0xda, 0x05, 0x9e, 0xf1, 0x22, 0x31, 0xc1, 0xa0, 0xff, 0xd7, 0x0f, 0x95, 0x73,
	0x0c, 0x47, 0x73, 0xe8, 0x19, 0xbc, 0x9b, 0x17, 0x3c, 0x25, 0x0b, 0xac, 0x36, 0x72, 0xfa, 0x37,
	0xa7, 0x2c, 0xb5, 0x1c, 0x1e, 0x7d, 0xf4, 0x06, 0x3a, 0x09, 0x13, 0x91, 0x2e, 0xbc, 0x15, 0xd0,
	0x70, 0x3c, 0x39, 0x1b, 0x00, 0x13, 0x26, 0xb4, 0x20, 0x06, 0xef, 0xb6, 0x7b, 0x0f, 0xec, 0xf6,
	0x1e, 0xf8, 0xbd, 0xf7, 0xc0, 0xf7, 0x83, 0x67, 0xed, 0x0e, 0x9e, 0xf5, 0xf3, 0xe0, 0x59, 0x5f,
	0x9e, 0x64, 0x44, 0xce, 0xbf, 0x4e, 0xfd, 0x19, 0xa7, 0xe6, 0x0a, 0x02, 0xbc, 0xa4, 0x41, 0x59,
	0xfd, 0xfd, 0x40, 0xae, 0x72, 0x2c, 0xa6, 0xb6, 0x3a, 0x82, 0xd7, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2c, 0x00, 0xe6, 0x48, 0x67, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FeeDenom != that1.FeeDenom {
		return false
	}
	if this.MinNameLength != that1.MinNameLength {
		return false
	}
	if this.MaxNameLength != that1.MaxNameLength {
		return false
	}
	return true
}
func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Names) > 0 {
		for iNdEx := len(m.Names) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Names[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Tlds) > 0 {
		for iNdEx := len(m.Tlds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tlds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxNameLength != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxNameLength))
		i--
		dAtA[i] = 0x18
	}
	if m.MinNameLength != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinNameLength))
		i--
		dAtA[i] = 0x10
	}
	if len(m.FeeDenom) > 0 {
		i -= len(m.FeeDenom)
		copy(dAtA[i:], m.FeeDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.FeeDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NameEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NameEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NameEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DnsRecords) > 0 {
		for iNdEx := len(m.DnsRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DnsRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Profile != nil {
		{
			size, err := m.Profile.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Tlds) > 0 {
		for _, e := range m.Tlds {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Names) > 0 {
		for _, e := range m.Names {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeeDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.MinNameLength != 0 {
		n += 1 + sovGenesis(uint64(m.MinNameLength))
	}
	if m.MaxNameLength != 0 {
		n += 1 + sovGenesis(uint64(m.MaxNameLength))
	}
	return n
}

func (m *NameEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Record.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Profile != nil {
		l = m.Profile.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.DnsRecords) > 0 {
		for _, e := range m.DnsRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tlds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tlds = append(m.Tlds, TLDConfig{})
			if err := m.Tlds[len(m.Tlds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Names", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Names = append(m.Names, NameEntry{})
			if err := m.Names[len(m.Names)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinNameLength", wireType)
			}
			m.MinNameLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinNameLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNameLength", wireType)
			}
			m.MaxNameLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNameLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NameEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NameEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NameEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Profile", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Profile == nil {
				m.Profile = &Profile{}
			}
			if err := m.Profile.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DnsRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DnsRecords = append(m.DnsRecords, DNSRecord{})
			if err := m.DnsRecords[len(m.DnsRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
