// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: xid/v1/query.proto

package xidv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_ResolveName_FullMethodName              = "/xid.v1.Query/ResolveName"
	Query_ReverseResolve_FullMethodName           = "/xid.v1.Query/ReverseResolve"
	Query_GetProfile_FullMethodName               = "/xid.v1.Query/GetProfile"
	Query_GetDNSRecords_FullMethodName            = "/xid.v1.Query/GetDNSRecords"
	Query_GetTLD_FullMethodName                   = "/xid.v1.Query/GetTLD"
	Query_ListTLDs_FullMethodName                 = "/xid.v1.Query/ListTLDs"
	Query_GetNamesByOwner_FullMethodName          = "/xid.v1.Query/GetNamesByOwner"
	Query_Params_FullMethodName                   = "/xid.v1.Query/Params"
	Query_GetRegistrationFee_FullMethodName       = "/xid.v1.Query/GetRegistrationFee"
	Query_ListAllNames_FullMethodName             = "/xid.v1.Query/ListAllNames"
	Query_GetStats_FullMethodName                 = "/xid.v1.Query/GetStats"
	Query_GetLinkedIdentities_FullMethodName      = "/xid.v1.Query/GetLinkedIdentities"
	Query_QueryStateDigest_FullMethodName         = "/xid.v1.Query/QueryStateDigest"
	Query_QueryAttestations_FullMethodName        = "/xid.v1.Query/QueryAttestations"
	Query_QueryStateSnapshot_FullMethodName       = "/xid.v1.Query/QueryStateSnapshot"
	Query_ResolveWithProof_FullMethodName         = "/xid.v1.Query/ResolveWithProof"
	Query_ReverseResolveByIdentity_FullMethodName = "/xid.v1.Query/ReverseResolveByIdentity"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the xid module's gRPC query service.
type QueryClient interface {
	// ResolveName resolves a name.tld to an owner address.
	ResolveName(ctx context.Context, in *QueryResolveNameRequest, opts ...grpc.CallOption) (*QueryResolveNameResponse, error)
	// ReverseResolve finds the primary name for an address.
	ReverseResolve(ctx context.Context, in *QueryReverseResolveRequest, opts ...grpc.CallOption) (*QueryReverseResolveResponse, error)
	// GetProfile returns the profile for a name.
	GetProfile(ctx context.Context, in *QueryGetProfileRequest, opts ...grpc.CallOption) (*QueryGetProfileResponse, error)
	// GetDNSRecords returns all DNS records for a name.
	GetDNSRecords(ctx context.Context, in *QueryGetDNSRecordsRequest, opts ...grpc.CallOption) (*QueryGetDNSRecordsResponse, error)
	// GetTLD returns the configuration for a TLD.
	GetTLD(ctx context.Context, in *QueryGetTLDRequest, opts ...grpc.CallOption) (*QueryGetTLDResponse, error)
	// ListTLDs returns all registered TLDs.
	ListTLDs(ctx context.Context, in *QueryListTLDsRequest, opts ...grpc.CallOption) (*QueryListTLDsResponse, error)
	// GetNamesByOwner returns all names owned by an address.
	GetNamesByOwner(ctx context.Context, in *QueryGetNamesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetNamesByOwnerResponse, error)
	// Params returns the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetRegistrationFee returns the registration fee for a given name and TLD.
	GetRegistrationFee(ctx context.Context, in *QueryGetRegistrationFeeRequest, opts ...grpc.CallOption) (*QueryGetRegistrationFeeResponse, error)
	// ListAllNames returns all registered names with pagination.
	ListAllNames(ctx context.Context, in *QueryListAllNamesRequest, opts ...grpc.CallOption) (*QueryListAllNamesResponse, error)
	// GetStats returns xID module statistics.
	GetStats(ctx context.Context, in *QueryGetStatsRequest, opts ...grpc.CallOption) (*QueryGetStatsResponse, error)
	// GetLinkedIdentities returns all linked identities for a name.
	GetLinkedIdentities(ctx context.Context, in *QueryGetLinkedIdentitiesRequest, opts ...grpc.CallOption) (*QueryGetLinkedIdentitiesResponse, error)
	// QueryStateDigest returns the current state digest of the xID module.
	QueryStateDigest(ctx context.Context, in *QueryStateDigestRequest, opts ...grpc.CallOption) (*QueryStateDigestResponse, error)
	// QueryAttestations returns validator attestations for a given digest.
	QueryAttestations(ctx context.Context, in *QueryAttestationsRequest, opts ...grpc.CallOption) (*QueryAttestationsResponse, error)
	// QueryStateSnapshot returns a paginated snapshot of all domain state.
	QueryStateSnapshot(ctx context.Context, in *QueryStateSnapshotRequest, opts ...grpc.CallOption) (*QueryStateSnapshotResponse, error)
	// ResolveWithProof resolves a name and returns a Merkle proof of inclusion.
	ResolveWithProof(ctx context.Context, in *QueryResolveWithProofRequest, opts ...grpc.CallOption) (*QueryResolveWithProofResponse, error)
	// ReverseResolveByIdentity finds the xID name associated with a linked identity address.
	ReverseResolveByIdentity(ctx context.Context, in *QueryReverseResolveByIdentityRequest, opts ...grpc.CallOption) (*QueryReverseResolveByIdentityResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ResolveName(ctx context.Context, in *QueryResolveNameRequest, opts ...grpc.CallOption) (*QueryResolveNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResolveNameResponse)
	err := c.cc.Invoke(ctx, Query_ResolveName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReverseResolve(ctx context.Context, in *QueryReverseResolveRequest, opts ...grpc.CallOption) (*QueryReverseResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReverseResolveResponse)
	err := c.cc.Invoke(ctx, Query_ReverseResolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProfile(ctx context.Context, in *QueryGetProfileRequest, opts ...grpc.CallOption) (*QueryGetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetProfileResponse)
	err := c.cc.Invoke(ctx, Query_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDNSRecords(ctx context.Context, in *QueryGetDNSRecordsRequest, opts ...grpc.CallOption) (*QueryGetDNSRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetDNSRecordsResponse)
	err := c.cc.Invoke(ctx, Query_GetDNSRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetTLD(ctx context.Context, in *QueryGetTLDRequest, opts ...grpc.CallOption) (*QueryGetTLDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetTLDResponse)
	err := c.cc.Invoke(ctx, Query_GetTLD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListTLDs(ctx context.Context, in *QueryListTLDsRequest, opts ...grpc.CallOption) (*QueryListTLDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListTLDsResponse)
	err := c.cc.Invoke(ctx, Query_ListTLDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetNamesByOwner(ctx context.Context, in *QueryGetNamesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetNamesByOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetNamesByOwnerResponse)
	err := c.cc.Invoke(ctx, Query_GetNamesByOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRegistrationFee(ctx context.Context, in *QueryGetRegistrationFeeRequest, opts ...grpc.CallOption) (*QueryGetRegistrationFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetRegistrationFeeResponse)
	err := c.cc.Invoke(ctx, Query_GetRegistrationFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListAllNames(ctx context.Context, in *QueryListAllNamesRequest, opts ...grpc.CallOption) (*QueryListAllNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListAllNamesResponse)
	err := c.cc.Invoke(ctx, Query_ListAllNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetStats(ctx context.Context, in *QueryGetStatsRequest, opts ...grpc.CallOption) (*QueryGetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetStatsResponse)
	err := c.cc.Invoke(ctx, Query_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLinkedIdentities(ctx context.Context, in *QueryGetLinkedIdentitiesRequest, opts ...grpc.CallOption) (*QueryGetLinkedIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetLinkedIdentitiesResponse)
	err := c.cc.Invoke(ctx, Query_GetLinkedIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryStateDigest(ctx context.Context, in *QueryStateDigestRequest, opts ...grpc.CallOption) (*QueryStateDigestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStateDigestResponse)
	err := c.cc.Invoke(ctx, Query_QueryStateDigest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryAttestations(ctx context.Context, in *QueryAttestationsRequest, opts ...grpc.CallOption) (*QueryAttestationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAttestationsResponse)
	err := c.cc.Invoke(ctx, Query_QueryAttestations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryStateSnapshot(ctx context.Context, in *QueryStateSnapshotRequest, opts ...grpc.CallOption) (*QueryStateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStateSnapshotResponse)
	err := c.cc.Invoke(ctx, Query_QueryStateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ResolveWithProof(ctx context.Context, in *QueryResolveWithProofRequest, opts ...grpc.CallOption) (*QueryResolveWithProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResolveWithProofResponse)
	err := c.cc.Invoke(ctx, Query_ResolveWithProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReverseResolveByIdentity(ctx context.Context, in *QueryReverseResolveByIdentityRequest, opts ...grpc.CallOption) (*QueryReverseResolveByIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReverseResolveByIdentityResponse)
	err := c.cc.Invoke(ctx, Query_ReverseResolveByIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the xid module's gRPC query service.
type QueryServer interface {
	// ResolveName resolves a name.tld to an owner address.
	ResolveName(context.Context, *QueryResolveNameRequest) (*QueryResolveNameResponse, error)
	// ReverseResolve finds the primary name for an address.
	ReverseResolve(context.Context, *QueryReverseResolveRequest) (*QueryReverseResolveResponse, error)
	// GetProfile returns the profile for a name.
	GetProfile(context.Context, *QueryGetProfileRequest) (*QueryGetProfileResponse, error)
	// GetDNSRecords returns all DNS records for a name.
	GetDNSRecords(context.Context, *QueryGetDNSRecordsRequest) (*QueryGetDNSRecordsResponse, error)
	// GetTLD returns the configuration for a TLD.
	GetTLD(context.Context, *QueryGetTLDRequest) (*QueryGetTLDResponse, error)
	// ListTLDs returns all registered TLDs.
	ListTLDs(context.Context, *QueryListTLDsRequest) (*QueryListTLDsResponse, error)
	// GetNamesByOwner returns all names owned by an address.
	GetNamesByOwner(context.Context, *QueryGetNamesByOwnerRequest) (*QueryGetNamesByOwnerResponse, error)
	// Params returns the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetRegistrationFee returns the registration fee for a given name and TLD.
	GetRegistrationFee(context.Context, *QueryGetRegistrationFeeRequest) (*QueryGetRegistrationFeeResponse, error)
	// ListAllNames returns all registered names with pagination.
	ListAllNames(context.Context, *QueryListAllNamesRequest) (*QueryListAllNamesResponse, error)
	// GetStats returns xID module statistics.
	GetStats(context.Context, *QueryGetStatsRequest) (*QueryGetStatsResponse, error)
	// GetLinkedIdentities returns all linked identities for a name.
	GetLinkedIdentities(context.Context, *QueryGetLinkedIdentitiesRequest) (*QueryGetLinkedIdentitiesResponse, error)
	// QueryStateDigest returns the current state digest of the xID module.
	QueryStateDigest(context.Context, *QueryStateDigestRequest) (*QueryStateDigestResponse, error)
	// QueryAttestations returns validator attestations for a given digest.
	QueryAttestations(context.Context, *QueryAttestationsRequest) (*QueryAttestationsResponse, error)
	// QueryStateSnapshot returns a paginated snapshot of all domain state.
	QueryStateSnapshot(context.Context, *QueryStateSnapshotRequest) (*QueryStateSnapshotResponse, error)
	// ResolveWithProof resolves a name and returns a Merkle proof of inclusion.
	ResolveWithProof(context.Context, *QueryResolveWithProofRequest) (*QueryResolveWithProofResponse, error)
	// ReverseResolveByIdentity finds the xID name associated with a linked identity address.
	ReverseResolveByIdentity(context.Context, *QueryReverseResolveByIdentityRequest) (*QueryReverseResolveByIdentityResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) ResolveName(context.Context, *QueryResolveNameRequest) (*QueryResolveNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveName not implemented")
}
func (UnimplementedQueryServer) ReverseResolve(context.Context, *QueryReverseResolveRequest) (*QueryReverseResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseResolve not implemented")
}
func (UnimplementedQueryServer) GetProfile(context.Context, *QueryGetProfileRequest) (*QueryGetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedQueryServer) GetDNSRecords(context.Context, *QueryGetDNSRecordsRequest) (*QueryGetDNSRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDNSRecords not implemented")
}
func (UnimplementedQueryServer) GetTLD(context.Context, *QueryGetTLDRequest) (*QueryGetTLDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTLD not implemented")
}
func (UnimplementedQueryServer) ListTLDs(context.Context, *QueryListTLDsRequest) (*QueryListTLDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTLDs not implemented")
}
func (UnimplementedQueryServer) GetNamesByOwner(context.Context, *QueryGetNamesByOwnerRequest) (*QueryGetNamesByOwnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamesByOwner not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetRegistrationFee(context.Context, *QueryGetRegistrationFeeRequest) (*QueryGetRegistrationFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistrationFee not implemented")
}
func (UnimplementedQueryServer) ListAllNames(context.Context, *QueryListAllNamesRequest) (*QueryListAllNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllNames not implemented")
}
func (UnimplementedQueryServer) GetStats(context.Context, *QueryGetStatsRequest) (*QueryGetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedQueryServer) GetLinkedIdentities(context.Context, *QueryGetLinkedIdentitiesRequest) (*QueryGetLinkedIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinkedIdentities not implemented")
}
func (UnimplementedQueryServer) QueryStateDigest(context.Context, *QueryStateDigestRequest) (*QueryStateDigestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryStateDigest not implemented")
}
func (UnimplementedQueryServer) QueryAttestations(context.Context, *QueryAttestationsRequest) (*QueryAttestationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAttestations not implemented")
}
func (UnimplementedQueryServer) QueryStateSnapshot(context.Context, *QueryStateSnapshotRequest) (*QueryStateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryStateSnapshot not implemented")
}
func (UnimplementedQueryServer) ResolveWithProof(context.Context, *QueryResolveWithProofRequest) (*QueryResolveWithProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveWithProof not implemented")
}
func (UnimplementedQueryServer) ReverseResolveByIdentity(context.Context, *QueryReverseResolveByIdentityRequest) (*QueryReverseResolveByIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseResolveByIdentity not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_ResolveName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryResolveNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ResolveName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ResolveName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ResolveName(ctx, req.(*QueryResolveNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReverseResolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReverseResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReverseResolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ReverseResolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReverseResolve(ctx, req.(*QueryReverseResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProfile(ctx, req.(*QueryGetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDNSRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDNSRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDNSRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetDNSRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDNSRecords(ctx, req.(*QueryGetDNSRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetTLD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTLDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTLD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetTLD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTLD(ctx, req.(*QueryGetTLDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListTLDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListTLDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListTLDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListTLDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListTLDs(ctx, req.(*QueryListTLDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetNamesByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNamesByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetNamesByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetNamesByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetNamesByOwner(ctx, req.(*QueryGetNamesByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRegistrationFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRegistrationFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRegistrationFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetRegistrationFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRegistrationFee(ctx, req.(*QueryGetRegistrationFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListAllNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListAllNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListAllNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListAllNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListAllNames(ctx, req.(*QueryListAllNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetStats(ctx, req.(*QueryGetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLinkedIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLinkedIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLinkedIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetLinkedIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLinkedIdentities(ctx, req.(*QueryGetLinkedIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryStateDigest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStateDigestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryStateDigest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryStateDigest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryStateDigest(ctx, req.(*QueryStateDigestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryAttestations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryAttestations(ctx, req.(*QueryAttestationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryStateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryStateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryStateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryStateSnapshot(ctx, req.(*QueryStateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ResolveWithProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryResolveWithProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ResolveWithProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ResolveWithProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ResolveWithProof(ctx, req.(*QueryResolveWithProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReverseResolveByIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReverseResolveByIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReverseResolveByIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ReverseResolveByIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReverseResolveByIdentity(ctx, req.(*QueryReverseResolveByIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xid.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveName",
			Handler:    _Query_ResolveName_Handler,
		},
		{
			MethodName: "ReverseResolve",
			Handler:    _Query_ReverseResolve_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Query_GetProfile_Handler,
		},
		{
			MethodName: "GetDNSRecords",
			Handler:    _Query_GetDNSRecords_Handler,
		},
		{
			MethodName: "GetTLD",
			Handler:    _Query_GetTLD_Handler,
		},
		{
			MethodName: "ListTLDs",
			Handler:    _Query_ListTLDs_Handler,
		},
		{
			MethodName: "GetNamesByOwner",
			Handler:    _Query_GetNamesByOwner_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetRegistrationFee",
			Handler:    _Query_GetRegistrationFee_Handler,
		},
		{
			MethodName: "ListAllNames",
			Handler:    _Query_ListAllNames_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Query_GetStats_Handler,
		},
		{
			MethodName: "GetLinkedIdentities",
			Handler:    _Query_GetLinkedIdentities_Handler,
		},
		{
			MethodName: "QueryStateDigest",
			Handler:    _Query_QueryStateDigest_Handler,
		},
		{
			MethodName: "QueryAttestations",
			Handler:    _Query_QueryAttestations_Handler,
		},
		{
			MethodName: "QueryStateSnapshot",
			Handler:    _Query_QueryStateSnapshot_Handler,
		},
		{
			MethodName: "ResolveWithProof",
			Handler:    _Query_ResolveWithProof_Handler,
		},
		{
			MethodName: "ReverseResolveByIdentity",
			Handler:    _Query_ReverseResolveByIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xid/v1/query.proto",
}
